services:
  - type: web
    name: whatsapp-twilio-bot
    env: python
    buildCommand: pip install -r bot/requirements.txt
    startCommand: python bot/app.py
    envVars:
      - key: PORT
        value: 10000
